In [18]:
import geopandas as gpd
import pandas as pds
import numpy as np
import os

ERROR! Session/line number was not unique in database. History logging moved to new session 75

In [2]:
# read in Geopackage file to work with
df = gpd.read_file('/home/eubtube/Documents/colline_automation/files/vector/colline_grid_joined_adj.gpkg')

In [3]:
df

,id,left,top,right,bottom,quadkey,fid_2,tileID,layer,path,col,row,Grid_Index,geometry
0,1.0,28.388672,0.878906,28.476562,0.791016,None,NaN,None,None,None,1.0,1.0,"1.0, 1.0","POLYGON ((28.38867 0.87891, 28.47656 0.87891, ..."
1,2.0,28.388672,0.791016,28.476562,0.703125,None,NaN,None,None,None,1.0,2.0,"2.0, 1.0","POLYGON ((28.38867 0.79102, 28.47656 0.79102, ..."
2,3.0,28.388672,0.703125,28.476562,0.615234,None,NaN,None,None,None,1.0,3.0,"3.0, 1.0","POLYGON ((28.38867 0.70312, 28.47656 0.70312, ..."
3,4.0,28.388672,0.615234,28.476562,0.527344,None,NaN,None,None,None,1.0,4.0,"4.0, 1.0","POLYGON ((28.38867 0.61523, 28.47656 0.61523, ..."
4,5.0,28.388672,0.527344,28.476562,0.439453,None,NaN,None,None,None,1.0,5.0,"5.0, 1.0","POLYGON ((28.38867 0.52734, 28.47656 0.52734, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1051,1052.0,31.201172,-1.494141,31.289062,-1.582031,None,NaN,None,None,None,33.0,28.0,"28.0, 33.0","POLYGON ((31.20117 -1.49414, 31.28906 -1.49414..."
1052,1053.0,31.201172,-1.582031,31.289062,-1.669922,None,NaN,None,None,None,33.0,29.0,"29.0, 33.0","POLYGON ((31.20117 -1.58203, 31.28906 -1.58203..."
1053,1054.0,31.201172,-1.669922,31.289062,-1.757812,None,NaN,None,None,None,33.0,30.0,"30.0, 33.0","POLYGON ((31.20117 -1.66992, 31.28906 -1.66992..."
1054,1055.0,31.201172,-1.757812,31.289062,-1.845703,None,NaN,None,None,None,33.0,31.0,"31.0, 33.0","POLYGON ((31.20117 -1.75781, 31.28906 -1.75781..."
1055,1056.0,31.201172,-1.845703,31.289062,-1.933594,None,NaN,None,None,None,33.0,32.0,"32.0, 33.0","POLYGON ((31.20117 -1.84570, 31.28906 -1.84570..."

In [4]:
# Make Row and Col values int

df['row'] = df['row'].astype(int)
df['col'] = df['col'].astype(int)
df

,id,left,top,right,bottom,quadkey,fid_2,tileID,layer,path,col,row,Grid_Index,geometry
0,1.0,28.388672,0.878906,28.476562,0.791016,None,NaN,None,None,None,1,1,"1.0, 1.0","POLYGON ((28.38867 0.87891, 28.47656 0.87891, ..."
1,2.0,28.388672,0.791016,28.476562,0.703125,None,NaN,None,None,None,1,2,"2.0, 1.0","POLYGON ((28.38867 0.79102, 28.47656 0.79102, ..."
2,3.0,28.388672,0.703125,28.476562,0.615234,None,NaN,None,None,None,1,3,"3.0, 1.0","POLYGON ((28.38867 0.70312, 28.47656 0.70312, ..."
3,4.0,28.388672,0.615234,28.476562,0.527344,None,NaN,None,None,None,1,4,"4.0, 1.0","POLYGON ((28.38867 0.61523, 28.47656 0.61523, ..."
4,5.0,28.388672,0.527344,28.476562,0.439453,None,NaN,None,None,None,1,5,"5.0, 1.0","POLYGON ((28.38867 0.52734, 28.47656 0.52734, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1051,1052.0,31.201172,-1.494141,31.289062,-1.582031,None,NaN,None,None,None,33,28,"28.0, 33.0","POLYGON ((31.20117 -1.49414, 31.28906 -1.49414..."
1052,1053.0,31.201172,-1.582031,31.289062,-1.669922,None,NaN,None,None,None,33,29,"29.0, 33.0","POLYGON ((31.20117 -1.58203, 31.28906 -1.58203..."
1053,1054.0,31.201172,-1.669922,31.289062,-1.757812,None,NaN,None,None,None,33,30,"30.0, 33.0","POLYGON ((31.20117 -1.66992, 31.28906 -1.66992..."
1054,1055.0,31.201172,-1.757812,31.289062,-1.845703,None,NaN,None,None,None,33,31,"31.0, 33.0","POLYGON ((31.20117 -1.75781, 31.28906 -1.75781..."
1055,1056.0,31.201172,-1.845703,31.289062,-1.933594,None,NaN,None,None,None,33,32,"32.0, 33.0","POLYGON ((31.20117 -1.84570, 31.28906 -1.84570..."

In [10]:
# Change NA Values to 0 for quadkeys
df['layer'].fillna(0,inplace=True)

In [5]:
# cascade column first
df.sort_values(['row', 'col'], inplace=True)
df

,id,left,top,right,bottom,quadkey,fid_2,tileID,layer,path,col,row,Grid_Index,geometry
0,1.0,28.388672,0.878906,28.476562,0.791016,None,NaN,None,None,None,1,1,"1.0, 1.0","POLYGON ((28.38867 0.87891, 28.47656 0.87891, ..."
32,33.0,28.476562,0.878906,28.564453,0.791016,None,NaN,None,None,None,2,1,"1.0, 2.0","POLYGON ((28.47656 0.87891, 28.56445 0.87891, ..."
64,65.0,28.564453,0.878906,28.652344,0.791016,None,NaN,None,None,None,3,1,"1.0, 3.0","POLYGON ((28.56445 0.87891, 28.65234 0.87891, ..."
96,97.0,28.652344,0.878906,28.740234,0.791016,None,NaN,None,None,None,4,1,"1.0, 4.0","POLYGON ((28.65234 0.87891, 28.74023 0.87891, ..."
128,129.0,28.740234,0.878906,28.828125,0.791016,None,NaN,None,None,None,5,1,"1.0, 5.0","POLYGON ((28.74023 0.87891, 28.82812 0.87891, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
927,928.0,30.849609,-1.845703,30.937500,-1.933594,None,NaN,None,None,None,29,32,"32.0, 29.0","POLYGON ((30.84961 -1.84570, 30.93750 -1.84570..."
959,960.0,30.937500,-1.845703,31.025391,-1.933594,None,NaN,None,None,None,30,32,"32.0, 30.0","POLYGON ((30.93750 -1.84570, 31.02539 -1.84570..."
991,992.0,31.025391,-1.845703,31.113281,-1.933594,None,NaN,None,None,None,31,32,"32.0, 31.0","POLYGON ((31.02539 -1.84570, 31.11328 -1.84570..."
1023,1024.0,31.113281,-1.845703,31.201172,-1.933594,None,NaN,None,None,None,32,32,"32.0, 32.0","POLYGON ((31.11328 -1.84570, 31.20117 -1.84570..."
1055,1056.0,31.201172,-1.845703,31.289062,-1.933594,None,NaN,None,None,None,33,32,"32.0, 33.0","POLYGON ((31.20117 -1.84570, 31.28906 -1.84570..."

In [8]:
# Add "grouprow" column for filter iteration
df['grouprow'] = df['row'].apply(lambda x: np.floor((x-1)/3+1).astype(int))
df

,id,left,top,right,bottom,quadkey,fid_2,tileID,layer,path,col,row,Grid_Index,geometry,grouprow,groupcol
0,1.0,28.388672,0.878906,28.476562,0.791016,None,NaN,None,None,None,1,1,"1.0, 1.0","POLYGON ((28.38867 0.87891, 28.47656 0.87891, ...",1,1.0
32,33.0,28.476562,0.878906,28.564453,0.791016,None,NaN,None,None,None,2,1,"1.0, 2.0","POLYGON ((28.47656 0.87891, 28.56445 0.87891, ...",1,1.0
64,65.0,28.564453,0.878906,28.652344,0.791016,None,NaN,None,None,None,3,1,"1.0, 3.0","POLYGON ((28.56445 0.87891, 28.65234 0.87891, ...",1,1.0
96,97.0,28.652344,0.878906,28.740234,0.791016,None,NaN,None,None,None,4,1,"1.0, 4.0","POLYGON ((28.65234 0.87891, 28.74023 0.87891, ...",1,2.0
128,129.0,28.740234,0.878906,28.828125,0.791016,None,NaN,None,None,None,5,1,"1.0, 5.0","POLYGON ((28.74023 0.87891, 28.82812 0.87891, ...",1,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
927,928.0,30.849609,-1.845703,30.937500,-1.933594,None,NaN,None,None,None,29,32,"32.0, 29.0","POLYGON ((30.84961 -1.84570, 30.93750 -1.84570...",11,10.0
959,960.0,30.937500,-1.845703,31.025391,-1.933594,None,NaN,None,None,None,30,32,"32.0, 30.0","POLYGON ((30.93750 -1.84570, 31.02539 -1.84570...",11,10.0
991,992.0,31.025391,-1.845703,31.113281,-1.933594,None,NaN,None,None,None,31,32,"32.0, 31.0","POLYGON ((31.02539 -1.84570, 31.11328 -1.84570...",11,11.0
1023,1024.0,31.113281,-1.845703,31.201172,-1.933594,None,NaN,None,None,None,32,32,"32.0, 32.0","POLYGON ((31.11328 -1.84570, 31.20117 -1.84570...",11,11.0
1055,1056.0,31.201172,-1.845703,31.289062,-1.933594,None,NaN,None,None,None,33,32,"32.0, 33.0","POLYGON ((31.20117 -1.84570, 31.28906 -1.84570...",11,11.0

In [12]:
# Add "groupcol" column for filter iteration
df['groupcol'] = df['col'].apply(lambda x: np.floor((x-1)/3+1).astype(int))
df

,id,left,top,right,bottom,quadkey,fid_2,tileID,layer,path,col,row,Grid_Index,geometry,grouprow,groupcol
0,1.0,28.388672,0.878906,28.476562,0.791016,None,NaN,None,0,None,1,1,"1.0, 1.0","POLYGON ((28.38867 0.87891, 28.47656 0.87891, ...",1,1
32,33.0,28.476562,0.878906,28.564453,0.791016,None,NaN,None,0,None,2,1,"1.0, 2.0","POLYGON ((28.47656 0.87891, 28.56445 0.87891, ...",1,1
64,65.0,28.564453,0.878906,28.652344,0.791016,None,NaN,None,0,None,3,1,"1.0, 3.0","POLYGON ((28.56445 0.87891, 28.65234 0.87891, ...",1,1
96,97.0,28.652344,0.878906,28.740234,0.791016,None,NaN,None,0,None,4,1,"1.0, 4.0","POLYGON ((28.65234 0.87891, 28.74023 0.87891, ...",1,2
128,129.0,28.740234,0.878906,28.828125,0.791016,None,NaN,None,0,None,5,1,"1.0, 5.0","POLYGON ((28.74023 0.87891, 28.82812 0.87891, ...",1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
927,928.0,30.849609,-1.845703,30.937500,-1.933594,None,NaN,None,0,None,29,32,"32.0, 29.0","POLYGON ((30.84961 -1.84570, 30.93750 -1.84570...",11,10
959,960.0,30.937500,-1.845703,31.025391,-1.933594,None,NaN,None,0,None,30,32,"32.0, 30.0","POLYGON ((30.93750 -1.84570, 31.02539 -1.84570...",11,10
991,992.0,31.025391,-1.845703,31.113281,-1.933594,None,NaN,None,0,None,31,32,"32.0, 31.0","POLYGON ((31.02539 -1.84570, 31.11328 -1.84570...",11,11
1023,1024.0,31.113281,-1.845703,31.201172,-1.933594,None,NaN,None,0,None,32,32,"32.0, 32.0","POLYGON ((31.11328 -1.84570, 31.20117 -1.84570...",11,11
1055,1056.0,31.201172,-1.845703,31.289062,-1.933594,None,NaN,None,0,None,33,32,"32.0, 33.0","POLYGON ((31.20117 -1.84570, 31.28906 -1.84570...",11,11

In [ ]:
df['3x3_group'] = (df['groupcol'].values.astype(str)).join("_").join(df['grouprow'].values.astype(str))
df

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-18-e8d94194647d>", line 1, in <module>
    df['3x3_group'] = (df['groupcol'].values.astype(str)).join("_").join(df['grouprow'].values.astype(str))
AttributeError: 'numpy.ndarray' object has no attribute 'join'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2044, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AttributeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1169, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/inspect.py", line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/inspect.py", line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/inspect.py", line 696, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/inspect.py", line 725, in getmodule
    file = getabsfile(object, _filename)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/inspect.py", line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/posixpath.py", line 383, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-18-e8d94194647d>", line 1, in <module>
    df['3x3_group'] = (df['groupcol'].values.astype(str)).join("_").join(df['grouprow'].values.astype(str))
AttributeError: 'numpy.ndarray' object has no attribute 'join'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2044, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AttributeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3337, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3434, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2047, in showtraceback
    value, tb, tb_offset=tb_offset)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1436, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1336, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1193, in structured_traceback
    tb_offset)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1150, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/ultratb.py", line 451, in find_recursion
    return len(records), 0
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2044, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'TypeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1169, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/inspect.py", line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/inspect.py", line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/inspect.py", line 696, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/inspect.py", line 725, in getmodule
    file = getabsfile(object, _filename)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/inspect.py", line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/posixpath.py", line 383, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-18-e8d94194647d>", line 1, in <module>
    df['3x3_group'] = (df['groupcol'].values.astype(str)).join("_").join(df['grouprow'].values.astype(str))
AttributeError: 'numpy.ndarray' object has no attribute 'join'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2044, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AttributeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3337, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3434, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2047, in showtraceback
    value, tb, tb_offset=tb_offset)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1436, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1336, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1193, in structured_traceback
    tb_offset)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1150, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/ultratb.py", line 451, in find_recursion
    return len(records), 0
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2044, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'TypeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2922, in _run_cell
    return runner(coro)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3146, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3356, in run_ast_nodes
    self.showtraceback()
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2047, in showtraceback
    value, tb, tb_offset=tb_offset)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1436, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1336, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1211, in structured_traceback
    chained_exceptions_tb_offset)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1150, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/ultratb.py", line 451, in find_recursion
    return len(records), 0
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2044, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'TypeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1169, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/site-packages/IPython/core/ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/inspect.py", line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/inspect.py", line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/inspect.py", line 696, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/inspect.py", line 725, in getmodule
    file = getabsfile(object, _filename)
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/inspect.py", line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File "/home/eubtube/anaconda3/envs/geoenv/lib/python3.7/posixpath.py", line 383, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

In [11]:
# Gives Dataframe with only tiles
df[df['layer'] != 0]

,id,left,top,right,bottom,quadkey,fid_2,tileID,layer,path,col,row,Grid_Index,geometry,grouprow,groupcol
640,641.0,30.146484,0.878906,30.234375,0.791016,None,1103.0,120101012113,120101012113,/media/ivan/Elements/DG-DRC tiles/tile_extents...,21,1,"1.0, 21.0","POLYGON ((30.14648 0.87891, 30.23438 0.87891, ...",1,7
609,610.0,30.058594,0.791016,30.146484,0.703125,None,1100.0,120101012110,120101012110,/media/ivan/Elements/DG-DRC tiles/tile_extents...,20,2,"2.0, 20.0","POLYGON ((30.05859 0.79102, 30.14648 0.79102, ...",1,7
641,642.0,30.146484,0.791016,30.234375,0.703125,None,1101.0,120101012111,120101012111,/media/ivan/Elements/DG-DRC tiles/tile_extents...,21,2,"2.0, 21.0","POLYGON ((30.14648 0.79102, 30.23438 0.79102, ...",1,7
98,99.0,28.652344,0.703125,28.740234,0.615234,None,780.0,120101000332,120101000332,/media/ivan/Elements/DG-DRC tiles/tile_extents...,4,3,"3.0, 4.0","POLYGON ((28.65234 0.70312, 28.74023 0.70312, ...",1,2
578,579.0,29.970703,0.703125,30.058594,0.615234,None,1033.0,120101010323,120101010323,/media/ivan/Elements/DG-DRC tiles/tile_extents...,19,3,"3.0, 19.0","POLYGON ((29.97070 0.70312, 30.05859 0.70312, ...",1,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,95.0,28.564453,-1.757812,28.652344,-1.845703,None,153.0,102323202123,102323202123,/media/ivan/Elements/DG-DRC tiles/tile_extents...,3,31,"31.0, 3.0","POLYGON ((28.56445 -1.75781, 28.65234 -1.75781...",11,1
126,127.0,28.652344,-1.757812,28.740234,-1.845703,None,155.0,102323202132,102323202132,/media/ivan/Elements/DG-DRC tiles/tile_extents...,4,31,"31.0, 4.0","POLYGON ((28.65234 -1.75781, 28.74023 -1.75781...",11,2
158,159.0,28.740234,-1.757812,28.828125,-1.845703,None,156.0,102323202133,102323202133,/media/ivan/Elements/DG-DRC tiles/tile_extents...,5,31,"31.0, 5.0","POLYGON ((28.74023 -1.75781, 28.82812 -1.75781...",11,2
95,96.0,28.564453,-1.845703,28.652344,-1.933594,None,151.0,102323202121,102323202121,/media/ivan/Elements/DG-DRC tiles/tile_extents...,3,32,"32.0, 3.0","POLYGON ((28.56445 -1.84570, 28.65234 -1.84570...",11,1
127,128.0,28.652344,-1.845703,28.740234,-1.933594,None,154.0,102323202130,102323202130,/media/ivan/Elements/DG-DRC tiles/tile_extents...,4,32,"32.0, 4.0","POLYGON ((28.65234 -1.84570, 28.74023 -1.84570...",11,2

In [ ]:
df['tileID'] = df['tileID'].fillna(0).astype(int)

In [ ]:
df['tileID'][344]

In [ ]:
df[df['tileID'] != 0].index

In [ ]:
# Pass a range of rows and columns, 
# spit the tiles associated with quadkeys at each position into an aoi file.
# How to only accept a range or coerce into a range?, exclusions?

def aoi(rowrange, colrange): 
    df_clipped = df[(df['row'] == rowrange[0]) & (df['col'] == colrange[0])]
    for x in rowrange:
        for y in colrange:
            df_clipped = df_clipped.append(df[(df['row'] == x) & (df['col'] == y)])
    
    df_clipped.drop(df_clipped.index[0],inplace=True)
    
    return df_clipped

aoi(range(7,10), range(9,14))

In [ ]:
# Write back to a new Geopackage File
df_clipped.to_file('/media/eubtube/Seagate Backup Plus Drive/Projects/[Project_ID]/Vector/aoi.gpkg', layer='aoi', driver="GPKG")

In [ ]:
## Make this a function to spit the tile quadkey into a txt file that can be read later.  
## Needs to be saved with a unique ID that will be used for the project.

dst_path = '/media/eubtube/Seagate Backup Plus Drive/Projects/[Project_ID]/Raster/tiles.txt'

file = open(dst_path, 'w')
for i, row in df_clipped.iterrows():
    if df_clipped['tileID'][i] != 0:
        print(str(df['tileID'][i]))
        file.write(str(df['tileID'][i]) + '\n')  
    else:
        pass
file.close()

In [ ]:
## REFERENCE

# Get all rows with certain value
df['row'][df['row'] == 10]

## SCRATCH

# for i, row in df.iterrows():
a = 1
b = 1
while df['row'][] == a  and df['col'] <= 3:
    print(df['tileID'])
    b+=1

#########################################################    
    
# attempts to start creating iterator
r = 1
c = 1
l = []

while r <= 3:
    r+=1
    c = c - 2
    while c <= 3:
        if 
        df['row'] == r & df['col'] == c:
            print(df['Grid_Index'][(df['row'] == r) & (df['col'] == c)])
        else:
            print("Didn't Work")
        c += 1

###############################################################        
        
r = 2
c = 1

print(df['Grid_Index'][(df['row'] == r) & (df['col'] == c)])

print(df['row'][(df['row'] == r) & (df['col'] == c)])

In [ ]:
# Check specific tile ID
df['layer'] = df['layer'].fillna(0).astype(int)
df[df['layer'] == 102323223202]

In [ ]:
# Iterates through everything and shows quadkey values
for i, row in df.iterrows():
    print(df['tileID'][i])

In [ ]:
# Serve up all the squares with tiles
for i, row in df.iterrows():
    if df['tileID'][i] != 0:
        print(df['tileID'][i])
    else:
        pass

In [ ]:
import numpy as np
d = {'rows': [1,1,1,2,2,2,3,3,3,1,1,1,2,2,2,3,3,3], 'cols': [1,2,3,1,2,3,1,2,3,4,5,6,4,5,6,4,5,6]}
df2 = pds.DataFrame(data=d)
df2

for i, row in df2.iterrows():
    #print(df2['rows'][i])
    print('{},{}'.format((df2['rows'][i]), (df2['cols'][i])))