In [36]:
import geopandas as gpd
import pandas as pds
import numpy as np
import os

In [ ]:
if __name__ == '__main__':
    parser = argparse.ArgumentParser()

    parser.add_argument("-if", "--input_file", help = "Geospatial File that will be analyzed here")
    parser.add_argument("-r", "--rows", help = "The row numbers that you will use")
    parser.add_argument("-op", "--output_path", help = "Output path for dddd")
    parser.add_argument("-pd", "--project_directory", help = "Directory path containing all your project files.")
    parser.add_argument("-qt", "--qgis_template", help = "QGIS project template")

    options = parser.parse_args()
    #print(options)
    #print(type(options))

    build_proj(options.input_file, options.rows, options.cols, options.output_dir_1, options.output_dir_2)

In [38]:
# TODO: Generalize this.

# read in Geopackage file to work with
#df = gpd.read_file('HOT_GCC_Collines/files/vector/colline_grid_joined_adj.gpkg')
df = gpd.read_file('colline_grid_joined_adj.gpkg')

In [39]:
df

,id,left,top,right,bottom,quadkey,fid_2,tileID,layer,path,col,row,Grid_Index,geometry
0,1.0,28.388672,0.878906,28.476562,0.791016,None,NaN,None,None,None,1.0,1.0,"1.0, 1.0","POLYGON ((28.38867 0.87891, 28.47656 0.87891, ..."
1,2.0,28.388672,0.791016,28.476562,0.703125,None,NaN,None,None,None,1.0,2.0,"2.0, 1.0","POLYGON ((28.38867 0.79102, 28.47656 0.79102, ..."
2,3.0,28.388672,0.703125,28.476562,0.615234,None,NaN,None,None,None,1.0,3.0,"3.0, 1.0","POLYGON ((28.38867 0.70312, 28.47656 0.70312, ..."
3,4.0,28.388672,0.615234,28.476562,0.527344,None,NaN,None,None,None,1.0,4.0,"4.0, 1.0","POLYGON ((28.38867 0.61523, 28.47656 0.61523, ..."
4,5.0,28.388672,0.527344,28.476562,0.439453,None,NaN,None,None,None,1.0,5.0,"5.0, 1.0","POLYGON ((28.38867 0.52734, 28.47656 0.52734, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1051,1052.0,31.201172,-1.494141,31.289062,-1.582031,None,NaN,None,None,None,33.0,28.0,"28.0, 33.0","POLYGON ((31.20117 -1.49414, 31.28906 -1.49414..."
1052,1053.0,31.201172,-1.582031,31.289062,-1.669922,None,NaN,None,None,None,33.0,29.0,"29.0, 33.0","POLYGON ((31.20117 -1.58203, 31.28906 -1.58203..."
1053,1054.0,31.201172,-1.669922,31.289062,-1.757812,None,NaN,None,None,None,33.0,30.0,"30.0, 33.0","POLYGON ((31.20117 -1.66992, 31.28906 -1.66992..."
1054,1055.0,31.201172,-1.757812,31.289062,-1.845703,None,NaN,None,None,None,33.0,31.0,"31.0, 33.0","POLYGON ((31.20117 -1.75781, 31.28906 -1.75781..."
1055,1056.0,31.201172,-1.845703,31.289062,-1.933594,None,NaN,None,None,None,33.0,32.0,"32.0, 33.0","POLYGON ((31.20117 -1.84570, 31.28906 -1.84570..."

In [40]:
# Make Row and Col values int

df['row'] = df['row'].astype(int)
df['col'] = df['col'].astype(int)
df

,id,left,top,right,bottom,quadkey,fid_2,tileID,layer,path,col,row,Grid_Index,geometry
0,1.0,28.388672,0.878906,28.476562,0.791016,None,NaN,None,None,None,1,1,"1.0, 1.0","POLYGON ((28.38867 0.87891, 28.47656 0.87891, ..."
1,2.0,28.388672,0.791016,28.476562,0.703125,None,NaN,None,None,None,1,2,"2.0, 1.0","POLYGON ((28.38867 0.79102, 28.47656 0.79102, ..."
2,3.0,28.388672,0.703125,28.476562,0.615234,None,NaN,None,None,None,1,3,"3.0, 1.0","POLYGON ((28.38867 0.70312, 28.47656 0.70312, ..."
3,4.0,28.388672,0.615234,28.476562,0.527344,None,NaN,None,None,None,1,4,"4.0, 1.0","POLYGON ((28.38867 0.61523, 28.47656 0.61523, ..."
4,5.0,28.388672,0.527344,28.476562,0.439453,None,NaN,None,None,None,1,5,"5.0, 1.0","POLYGON ((28.38867 0.52734, 28.47656 0.52734, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1051,1052.0,31.201172,-1.494141,31.289062,-1.582031,None,NaN,None,None,None,33,28,"28.0, 33.0","POLYGON ((31.20117 -1.49414, 31.28906 -1.49414..."
1052,1053.0,31.201172,-1.582031,31.289062,-1.669922,None,NaN,None,None,None,33,29,"29.0, 33.0","POLYGON ((31.20117 -1.58203, 31.28906 -1.58203..."
1053,1054.0,31.201172,-1.669922,31.289062,-1.757812,None,NaN,None,None,None,33,30,"30.0, 33.0","POLYGON ((31.20117 -1.66992, 31.28906 -1.66992..."
1054,1055.0,31.201172,-1.757812,31.289062,-1.845703,None,NaN,None,None,None,33,31,"31.0, 33.0","POLYGON ((31.20117 -1.75781, 31.28906 -1.75781..."
1055,1056.0,31.201172,-1.845703,31.289062,-1.933594,None,NaN,None,None,None,33,32,"32.0, 33.0","POLYGON ((31.20117 -1.84570, 31.28906 -1.84570..."

In [41]:
# Change NA Values to 0 for quadkeys in 'layer' column
df['layer'].fillna(0,inplace=True)

In [42]:
# cascade column first
df.sort_values(['row', 'col'], inplace=True)
df

,id,left,top,right,bottom,quadkey,fid_2,tileID,layer,path,col,row,Grid_Index,geometry
0,1.0,28.388672,0.878906,28.476562,0.791016,None,NaN,None,0,None,1,1,"1.0, 1.0","POLYGON ((28.38867 0.87891, 28.47656 0.87891, ..."
32,33.0,28.476562,0.878906,28.564453,0.791016,None,NaN,None,0,None,2,1,"1.0, 2.0","POLYGON ((28.47656 0.87891, 28.56445 0.87891, ..."
64,65.0,28.564453,0.878906,28.652344,0.791016,None,NaN,None,0,None,3,1,"1.0, 3.0","POLYGON ((28.56445 0.87891, 28.65234 0.87891, ..."
96,97.0,28.652344,0.878906,28.740234,0.791016,None,NaN,None,0,None,4,1,"1.0, 4.0","POLYGON ((28.65234 0.87891, 28.74023 0.87891, ..."
128,129.0,28.740234,0.878906,28.828125,0.791016,None,NaN,None,0,None,5,1,"1.0, 5.0","POLYGON ((28.74023 0.87891, 28.82812 0.87891, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
927,928.0,30.849609,-1.845703,30.937500,-1.933594,None,NaN,None,0,None,29,32,"32.0, 29.0","POLYGON ((30.84961 -1.84570, 30.93750 -1.84570..."
959,960.0,30.937500,-1.845703,31.025391,-1.933594,None,NaN,None,0,None,30,32,"32.0, 30.0","POLYGON ((30.93750 -1.84570, 31.02539 -1.84570..."
991,992.0,31.025391,-1.845703,31.113281,-1.933594,None,NaN,None,0,None,31,32,"32.0, 31.0","POLYGON ((31.02539 -1.84570, 31.11328 -1.84570..."
1023,1024.0,31.113281,-1.845703,31.201172,-1.933594,None,NaN,None,0,None,32,32,"32.0, 32.0","POLYGON ((31.11328 -1.84570, 31.20117 -1.84570..."
1055,1056.0,31.201172,-1.845703,31.289062,-1.933594,None,NaN,None,0,None,33,32,"32.0, 33.0","POLYGON ((31.20117 -1.84570, 31.28906 -1.84570..."

In [46]:
# Make"grouprow" and "groupcol" for filter iteration

def make_group_cols(df,nrow,ncol):
    # A function to make new 
    df['grouprow'] = df['row'].apply(lambda x: np.floor((x-1)/nrow+1).astype(int))
    df['groupcol'] = df['col'].apply(lambda x: np.floor((x-1)/ncol+1).astype(int))
    return df
    
make_group_cols(df,3,3)

,id,left,top,right,bottom,quadkey,fid_2,tileID,layer,path,col,row,Grid_Index,geometry,grouprow,groupcol
0,1.0,28.388672,0.878906,28.476562,0.791016,None,NaN,None,0,None,1,1,"1.0, 1.0","POLYGON ((28.38867 0.87891, 28.47656 0.87891, ...",1,1
32,33.0,28.476562,0.878906,28.564453,0.791016,None,NaN,None,0,None,2,1,"1.0, 2.0","POLYGON ((28.47656 0.87891, 28.56445 0.87891, ...",1,1
64,65.0,28.564453,0.878906,28.652344,0.791016,None,NaN,None,0,None,3,1,"1.0, 3.0","POLYGON ((28.56445 0.87891, 28.65234 0.87891, ...",1,1
96,97.0,28.652344,0.878906,28.740234,0.791016,None,NaN,None,0,None,4,1,"1.0, 4.0","POLYGON ((28.65234 0.87891, 28.74023 0.87891, ...",1,2
128,129.0,28.740234,0.878906,28.828125,0.791016,None,NaN,None,0,None,5,1,"1.0, 5.0","POLYGON ((28.74023 0.87891, 28.82812 0.87891, ...",1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
927,928.0,30.849609,-1.845703,30.937500,-1.933594,None,NaN,None,0,None,29,32,"32.0, 29.0","POLYGON ((30.84961 -1.84570, 30.93750 -1.84570...",11,10
959,960.0,30.937500,-1.845703,31.025391,-1.933594,None,NaN,None,0,None,30,32,"32.0, 30.0","POLYGON ((30.93750 -1.84570, 31.02539 -1.84570...",11,10
991,992.0,31.025391,-1.845703,31.113281,-1.933594,None,NaN,None,0,None,31,32,"32.0, 31.0","POLYGON ((31.02539 -1.84570, 31.11328 -1.84570...",11,11
1023,1024.0,31.113281,-1.845703,31.201172,-1.933594,None,NaN,None,0,None,32,32,"32.0, 32.0","POLYGON ((31.11328 -1.84570, 31.20117 -1.84570...",11,11
1055,1056.0,31.201172,-1.845703,31.289062,-1.933594,None,NaN,None,0,None,33,32,"32.0, 33.0","POLYGON ((31.20117 -1.84570, 31.28906 -1.84570...",11,11

In [70]:
# Snippet that makes a column for project name
def make_ProjName_col(df):
    df['ProjectName'] = "project" + "_" + df['groupcol'].astype('string') + "_" + df['grouprow'].astype('string')

make_ProjName_col(df)

df

,id,left,top,right,bottom,quadkey,fid_2,tileID,layer,path,col,row,Grid_Index,geometry,grouprow,groupcol,ProjectName
0,1.0,28.388672,0.878906,28.476562,0.791016,None,NaN,None,0,None,1,1,"1.0, 1.0","POLYGON ((28.38867 0.87891, 28.47656 0.87891, ...",1,1,project_1_1
32,33.0,28.476562,0.878906,28.564453,0.791016,None,NaN,None,0,None,2,1,"1.0, 2.0","POLYGON ((28.47656 0.87891, 28.56445 0.87891, ...",1,1,project_1_1
64,65.0,28.564453,0.878906,28.652344,0.791016,None,NaN,None,0,None,3,1,"1.0, 3.0","POLYGON ((28.56445 0.87891, 28.65234 0.87891, ...",1,1,project_1_1
96,97.0,28.652344,0.878906,28.740234,0.791016,None,NaN,None,0,None,4,1,"1.0, 4.0","POLYGON ((28.65234 0.87891, 28.74023 0.87891, ...",1,2,project_2_1
128,129.0,28.740234,0.878906,28.828125,0.791016,None,NaN,None,0,None,5,1,"1.0, 5.0","POLYGON ((28.74023 0.87891, 28.82812 0.87891, ...",1,2,project_2_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
927,928.0,30.849609,-1.845703,30.937500,-1.933594,None,NaN,None,0,None,29,32,"32.0, 29.0","POLYGON ((30.84961 -1.84570, 30.93750 -1.84570...",11,10,project_10_11
959,960.0,30.937500,-1.845703,31.025391,-1.933594,None,NaN,None,0,None,30,32,"32.0, 30.0","POLYGON ((30.93750 -1.84570, 31.02539 -1.84570...",11,10,project_10_11
991,992.0,31.025391,-1.845703,31.113281,-1.933594,None,NaN,None,0,None,31,32,"32.0, 31.0","POLYGON ((31.02539 -1.84570, 31.11328 -1.84570...",11,11,project_11_11
1023,1024.0,31.113281,-1.845703,31.201172,-1.933594,None,NaN,None,0,None,32,32,"32.0, 32.0","POLYGON ((31.11328 -1.84570, 31.20117 -1.84570...",11,11,project_11_11
1055,1056.0,31.201172,-1.845703,31.289062,-1.933594,None,NaN,None,0,None,33,32,"32.0, 33.0","POLYGON ((31.20117 -1.84570, 31.28906 -1.84570...",11,11,project_11_11

In [20]:
# Gives filtered Dataframe with only tiles
df[df['layer'] != 0]

,id,left,top,right,bottom,quadkey,fid_2,tileID,layer,path,col,row,Grid_Index,geometry,grouprow,groupcol
640,641.0,30.146484,0.878906,30.234375,0.791016,None,1103.0,120101012113,120101012113,/media/ivan/Elements/DG-DRC tiles/tile_extents...,21,1,"1.0, 21.0","POLYGON ((30.14648 0.87891, 30.23438 0.87891, ...",1,7
609,610.0,30.058594,0.791016,30.146484,0.703125,None,1100.0,120101012110,120101012110,/media/ivan/Elements/DG-DRC tiles/tile_extents...,20,2,"2.0, 20.0","POLYGON ((30.05859 0.79102, 30.14648 0.79102, ...",1,7
641,642.0,30.146484,0.791016,30.234375,0.703125,None,1101.0,120101012111,120101012111,/media/ivan/Elements/DG-DRC tiles/tile_extents...,21,2,"2.0, 21.0","POLYGON ((30.14648 0.79102, 30.23438 0.79102, ...",1,7
98,99.0,28.652344,0.703125,28.740234,0.615234,None,780.0,120101000332,120101000332,/media/ivan/Elements/DG-DRC tiles/tile_extents...,4,3,"3.0, 4.0","POLYGON ((28.65234 0.70312, 28.74023 0.70312, ...",1,2
578,579.0,29.970703,0.703125,30.058594,0.615234,None,1033.0,120101010323,120101010323,/media/ivan/Elements/DG-DRC tiles/tile_extents...,19,3,"3.0, 19.0","POLYGON ((29.97070 0.70312, 30.05859 0.70312, ...",1,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,95.0,28.564453,-1.757812,28.652344,-1.845703,None,153.0,102323202123,102323202123,/media/ivan/Elements/DG-DRC tiles/tile_extents...,3,31,"31.0, 3.0","POLYGON ((28.56445 -1.75781, 28.65234 -1.75781...",11,1
126,127.0,28.652344,-1.757812,28.740234,-1.845703,None,155.0,102323202132,102323202132,/media/ivan/Elements/DG-DRC tiles/tile_extents...,4,31,"31.0, 4.0","POLYGON ((28.65234 -1.75781, 28.74023 -1.75781...",11,2
158,159.0,28.740234,-1.757812,28.828125,-1.845703,None,156.0,102323202133,102323202133,/media/ivan/Elements/DG-DRC tiles/tile_extents...,5,31,"31.0, 5.0","POLYGON ((28.74023 -1.75781, 28.82812 -1.75781...",11,2
95,96.0,28.564453,-1.845703,28.652344,-1.933594,None,151.0,102323202121,102323202121,/media/ivan/Elements/DG-DRC tiles/tile_extents...,3,32,"32.0, 3.0","POLYGON ((28.56445 -1.84570, 28.65234 -1.84570...",11,1
127,128.0,28.652344,-1.845703,28.740234,-1.933594,None,154.0,102323202130,102323202130,/media/ivan/Elements/DG-DRC tiles/tile_extents...,4,32,"32.0, 4.0","POLYGON ((28.65234 -1.84570, 28.74023 -1.84570...",11,2

In [29]:
df['tileID'] = df['tileID'].fillna(0).astype(int)

In [22]:
df['tileID'][344]

102323221103

In [23]:
df[df['tileID'] != 0].index

Int64Index([640, 609, 641,  98, 578, 610, 642,  67,  99, 131,
            ...
            125, 157, 189, 221, 253,  94, 126, 158,  95, 127],
           dtype='int64', length=423)

In [66]:
## Fancy stuff, but if we just make aois by iterating through unique identifiers (created above), we won't need to do this at all.

# Pass a range of rows and columns, 
# spit the tiles associated with quadkeys at each position into an aoi file.


def aoi(r1,r2,c1,c2):
    
    rowrange=range(r1-1,(r2+1)) #add one to the second so that range stays with input.
    colrange=range(c1-1,(c2+1)) 
    
    df_clipped = df[(df['row'] == rowrange[0]) & (df['col'] == colrange[0])]
    for x in rowrange:
        for y in colrange:
            df_clipped = df_clipped.append(df[(df['row'] == x) & (df['col'] == y)])
    
    df_filter = df_clipped[df_clipped['layer'] != 0] # Filters only layers with tiles
    #df_clipped.drop(df_clipped.index[0],inplace=True)
    
    return df_filter

aoi(3,6,3,6)

,id,left,top,right,bottom,quadkey,fid_2,tileID,layer,path,col,row,Grid_Index,geometry,grouprow,groupcol,ProjectName
98,99.0,28.652344,0.703125,28.740234,0.615234,None,780.0,120101000332,120101000332,/media/ivan/Elements/DG-DRC tiles/tile_extents...,4,3,"3.0, 4.0","POLYGON ((28.65234 0.70312, 28.74023 0.70312, ...",1,2,project_2_1
67,68.0,28.564453,0.615234,28.652344,0.527344,None,775.0,120101000321,120101000321,/media/ivan/Elements/DG-DRC tiles/tile_extents...,3,4,"4.0, 3.0","POLYGON ((28.56445 0.61523, 28.65234 0.61523, ...",2,1,project_1_2
99,100.0,28.652344,0.615234,28.740234,0.527344,None,778.0,120101000330,120101000330,/media/ivan/Elements/DG-DRC tiles/tile_extents...,4,4,"4.0, 4.0","POLYGON ((28.65234 0.61523, 28.74023 0.61523, ...",2,2,project_2_2
131,132.0,28.740234,0.615234,28.828125,0.527344,None,779.0,120101000331,120101000331,/media/ivan/Elements/DG-DRC tiles/tile_extents...,5,4,"4.0, 5.0","POLYGON ((28.74023 0.61523, 28.82812 0.61523, ...",2,2,project_2_2
163,164.0,28.828125,0.615234,28.916016,0.527344,None,822.0,120101001220,120101001220,/media/ivan/Elements/DG-DRC tiles/tile_extents...,6,4,"4.0, 6.0","POLYGON ((28.82812 0.61523, 28.91602 0.61523, ...",2,2,project_2_2
68,69.0,28.564453,0.527344,28.652344,0.439453,None,769.0,120101000303,120101000303,/media/ivan/Elements/DG-DRC tiles/tile_extents...,3,5,"5.0, 3.0","POLYGON ((28.56445 0.52734, 28.65234 0.52734, ...",2,1,project_1_2
100,101.0,28.652344,0.527344,28.740234,0.439453,None,772.0,120101000312,120101000312,/media/ivan/Elements/DG-DRC tiles/tile_extents...,4,5,"5.0, 4.0","POLYGON ((28.65234 0.52734, 28.74023 0.52734, ...",2,2,project_2_2
132,133.0,28.740234,0.527344,28.828125,0.439453,None,773.0,120101000313,120101000313,/media/ivan/Elements/DG-DRC tiles/tile_extents...,5,5,"5.0, 5.0","POLYGON ((28.74023 0.52734, 28.82812 0.52734, ...",2,2,project_2_2
164,165.0,28.828125,0.527344,28.916016,0.439453,None,816.0,120101001202,120101001202,/media/ivan/Elements/DG-DRC tiles/tile_extents...,6,5,"5.0, 6.0","POLYGON ((28.82812 0.52734, 28.91602 0.52734, ...",2,2,project_2_2
69,70.0,28.564453,0.439453,28.652344,0.351562,None,767.0,120101000301,120101000301,/media/ivan/Elements/DG-DRC tiles/tile_extents...,3,6,"6.0, 3.0","POLYGON ((28.56445 0.43945, 28.65234 0.43945, ...",2,1,project_1_2
101,102.0,28.652344,0.439453,28.740234,0.351562,None,770.0,120101000310,120101000310,/media/ivan/Elements/DG-DRC tiles/tile_extents...,4,6,"6.0, 4.0","POLYGON ((28.65234 0.43945, 28.74023 0.43945, ...",2,2,project_2_2
133,134.0,28.740234,0.439453,28.828125,0.351562,None,771.0,120101000311,120101000311,/media/ivan/Elements/DG-DRC tiles/tile_extents...,5,6,"6.0, 5.0","POLYGON ((28.74023 0.43945, 28.82812 0.43945, ...",2,2,project_2_2
165,166.0,28.828125,0.439453,28.916016,0.351562,None,814.0,120101001200,120101001200,/media/ivan/Elements/DG-DRC tiles/tile_extents...,6,6,"6.0, 6.0","POLYGON ((28.82812 0.43945, 28.91602 0.43945, ...",2,2,project_2_2

In [ ]:
# Write back to a new Geopackage File
pathr = 
df_filter.to_file('[Project_ID]/Vector/aoi.gpkg', layer='aoi', driver="GPKG")

In [ ]:
## Make this a function to spit the tile quadkey into a txt file that can be read later.  
## Needs to be saved with a unique ID that will be used for the project.

dst_path = '/media/eubtube/Seagate Backup Plus Drive/Projects/[Project_ID]/Raster/tiles.txt'

file = open(dst_path, 'w')
for i, row in df_clipped.iterrows():
    if df_clipped['tileID'][i] != 0:
        print(str(df['tileID'][i]))
        file.write(str(df['tileID'][i]) + '\n')  
    else:
        pass
file.close()

In [ ]:
## REFERENCE

# Get all rows with certain value
df['row'][df['row'] == 10]

## SCRATCH

# for i, row in df.iterrows():
a = 1
b = 1
while df['row'][] == a  and df['col'] <= 3:
    print(df['tileID'])
    b+=1

#########################################################    
    
# attempts to start creating iterator
r = 1
c = 1
l = []

while r <= 3:
    r+=1
    c = c - 2
    while c <= 3:
        if 
        df['row'] == r & df['col'] == c:
            print(df['Grid_Index'][(df['row'] == r) & (df['col'] == c)])
        else:
            print("Didn't Work")
        c += 1

###############################################################        
        
r = 2
c = 1

print(df['Grid_Index'][(df['row'] == r) & (df['col'] == c)])

print(df['row'][(df['row'] == r) & (df['col'] == c)])

In [67]:
# Check specific tile ID
df['layer'] = df['layer'].fillna(0).astype(int)
df[df['layer'] == 102323223202]

,id,left,top,right,bottom,quadkey,fid_2,tileID,layer,path,col,row,Grid_Index,geometry,grouprow,groupcol,ProjectName
172,173.0,28.828125,-0.175781,28.916016,-0.263672,None,443.0,102323223202,102323223202,/media/ivan/Elements/DG-DRC tiles/tile_extents...,6,13,"13.0, 6.0","POLYGON ((28.82812 -0.17578, 28.91602 -0.17578...",5,2,project_2_5

In [ ]:
# Iterates through everything and shows quadkey values
for i, row in df.iterrows():
    print(df['tileID'][i])

In [ ]:
# Serve up all the squares with tiles
for i, row in df.iterrows():
    if df['tileID'][i] != 0:
        print(df['tileID'][i])
    else:
        pass

In [ ]:
import numpy as np
d = {'rows': [1,1,1,2,2,2,3,3,3,1,1,1,2,2,2,3,3,3], 'cols': [1,2,3,1,2,3,1,2,3,4,5,6,4,5,6,4,5,6]}
df2 = pds.DataFrame(data=d)
df2

for i, row in df2.iterrows():
    #print(df2['rows'][i])
    print('{},{}'.format((df2['rows'][i]), (df2['cols'][i])))